project_dir: "./"
dataset_root: "/mnt/hdd0/datasets"
dataset_name: "celeba/img_align_celeba"
save_dir : "./models"

train:
  epochs: 70
  batch_size: 16
  num_FAN_modules: 2
  num_workers: 12
  # Learning rate setting
  start_decay: 60
  start_lr: 2.5e-4
  final_lr: 1.0e-5

test:
  

